#!/bin/bash

# xpra attach ssh:10.1.0.100:42
# "C:\Program Files\Xpra\Xpra.exe" --window-close=disconnect attach tcp://10.1.0.100:1337

export XDG_RUNTIME_DIR="/tmp/emacsd/"
mkdir -p $XDG_RUNTIME_DIR

XPRA="xpra --socket-dir=/tmp/emacsd/"
DISPLAY=42
ADDR=0.0.0.0:1337

case $1 in
    start)
        $XPRA start :$DISPLAY \
              --bind-tcp=$ADDR \
              --html=on \
              --microphone=no \
              --pulseaudio=no \
              --speaker=no \
              --webcam=no \
              --xsettings=no \
              --clipboard=yes \
              --file-transfer=on \
              --mdns=no \
              --printing=no \
              --start="emacs -l ../../init.el"
        ;;
    stop)
        $XPRA stop :$DISPLAY
        ;;
    *)
        echo "start/stop"
        ;;
esac
