#!/bin/bash

export XDG_RUNTIME_DIR="/tmp/emacsd/"
mkdir -p $XDG_RUNTIME_DIR

case $1 in
    start)
        xpra start :42 --bind-tcp=0.0.0.0:10000 --start="emacs -l ../init.el"
        ;;
    stop)
        xpra stop :42
        ;;
    # connect)
    #     xpra attach ssh:10.1.0.100:42
    #     ;;
    *)
        echo "start/stop"
        ;;
esac
