version: "3.7"
   
services:
  emacs:
    image: nakkaya/emacs:latest
    privileged: true
    hostname: lambda
    restart: always
    volumes:
      - storage:/storage
      - mvn_db:/home/nakkaya/.m2
      - lein_db:/home/nakkaya/.lein
    ports:
      # Webdav
      - "127.0.0.1:1010:1010"
      # CLI
      - "127.0.0.1:8080:8080"
      # GUI
      - "127.0.0.1:9090:9090"
    #environment:
      #- PASSWD=pass

volumes:
  storage:
  mvn_db:
  lein_db:
