version: "3.7"
   
services:
  emacs:
    image: ghcr.io/nakkaya/emacs-cpu:latest
    privileged: true
    security_opt:
      - seccomp:unconfined
    hostname: emacsd
    restart: always
    volumes:
      - home:/home/core
    ports:
      # SSH
      - "2222:2222"
      # Webdav
      - "4242:4242"
      # GUI
      - "9090:9090"
    #environment:
      #- PASSWD=pass

volumes:
  home:
