FROM ubuntu:20.04
ENV DISTRO=focal

ENV USER="nakkaya" \
    UID=1000 \
    TZ=Asia/Nicosia

RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
RUN apt-get update && apt-get upgrade -y

# Set Timezone
#
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    apt-get install tzdata -y --no-install-recommends \
    dpkg-reconfigure tzdata

# Install Packages
#
RUN apt-get install \
    # Misc
    sudo curl iputils-ping bash-completion \
    unzip wget htop xz-utils \
    graphviz postgresql-client qutebrowser\
    # Backup & Storage
    rclone git git-annex git-annex-remote-rclone \
    apt-transport-https apache2-utils \
    # Java
    openjdk-11-jdk maven  \
    # C/C++
    build-essential clang clangd cmake cppcheck valgrind \
    # Emacs Native Comp Deps
    gcc-10 g++-10 libgccjit0 libgccjit-10-dev libjansson-dev \
    # Python
    python3 python3-dev python3-pip \
    # Latex
    texlive-latex-base texlive-xetex texlive-lang-english \
    texlive-lang-european texlive-plain-generic pandoc latexmk \
    # PDF Tools
    libpng-dev zlib1g-dev libpoppler-glib-dev \
    libpoppler-private-dev imagemagick \
    # For Teensy
    libxft2 \
    -y --no-install-recommends

RUN apt-get install ispell -y

# Install Terraform
#
RUN apt-get install -y --no-install-recommends gnupg software-properties-common curl && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
    apt-add-repository \
    "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
    apt-get update && apt-get install -y --no-install-recommends terraform

# Clean Apt
#
RUN apt-get clean && apt-get autoclean

# Configure Python
#
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
    pip install invoke \
    python-lsp-server[all] \
    ansible \
    jupyterlab jupyter-console remote_ikernel \
    requests pillow numpy matplotlib \
    pyinotify pyxdg paramiko

# Install Clojure
#
RUN wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -P /usr/bin/ && \
    chmod 755 /usr/bin/lein

# Install AWS CLI
#
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip && \
    pip install boto3

# Arduino
#
RUN wget http://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz && \
    tar xf arduino-1.8.13-linux64.tar.xz && \
    mv arduino-1.8.13 /usr/local/share/arduino && \
    ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino && \
    ln -s /usr/local/share/arduino/arduino-builder /usr/local/bin/arduino-builder && \
    rm -rf arduino-1.8.13-linux64.tar.xz && \
    arduino --install-boards arduino:sam && \
    wget https://www.pjrc.com/teensy/td_153/TeensyduinoInstall.linux64 && \
    chmod +x TeensyduinoInstall.linux64 && \
    ./TeensyduinoInstall.linux64  --dir=/usr/local/share/arduino && \
    rm -rf TeensyduinoInstall.linux64

# Setup User
#
COPY resources/conf/bashrc /home/$USER/.bashrc
ADD resources/media/JetBrainsMono.ttf /usr/local/share/fonts

RUN useradd -u $UID -s /bin/bash $USER && \
    usermod -a -G dialout $USER && \
    adduser $USER sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    #
    mkdir -p /home/$USER/ && \
    mkdir /storage && \
    touch /home/$USER/.sudo_as_admin_successful
