FROM ubuntu:20.04
ARG UID=1000
ARG USER="nakkaya"

RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
RUN apt-get update && apt-get upgrade -y

# Set Timezone
#
ENV TZ=UTC \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install tzdata -y --no-install-recommends
RUN dpkg-reconfigure --frontend noninteractive tzdata

# Install Packages
#
RUN apt-get install sudo curl iputils-ping bash-completion unzip wget htop -y --no-install-recommends
RUN apt-get install rclone git git-annex git-annex-remote-rclone -y --no-install-recommends
RUN apt-get install postgresql-client -y --no-install-recommends
RUN apt-get install openjdk-11-jdk maven -y --no-install-recommends
RUN apt-get install build-essential -y --no-install-recommends
RUN apt-get install python3 python3-pip  -y --no-install-recommends
RUN apt-get install ispell -y

# Install Terraform
#
RUN apt-get install -y --no-install-recommends gnupg software-properties-common curl
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt-get update && apt-get install -y --no-install-recommends terraform

# Install NodeJS
#
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install nodejs -y --no-install-recommends 

# Latex
#
RUN apt-get install texlive-latex-base texlive-xetex texlive-lang-english texlive-lang-european latexmk -y --no-install-recommends

# Clean Apt
#
RUN apt-get clean && apt-get autoclean

# PIP Packages
#
RUN pip3 install invoke pylint ansible PyWebDAV3
RUN pip3 install jupyterlab jupyter-console remote_ikernel nbstripout
RUN pip3 install requests pillow numpy matplotlib

# Install Clojure
#
ADD https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein /usr/bin/lein
RUN chmod 755 /usr/bin/lein

# Install Go
#
ADD https://golang.org/dl/go1.16.5.linux-amd64.tar.gz /
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
RUN ln -s /usr/local/go/bin/go /usr/bin/go

# Install AWS CLI
#
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm awscliv2.zip
RUN pip3 install boto3

# Setup User
#
RUN useradd -u $UID -s /bin/bash $USER
RUN adduser $USER sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir /home/$USER/
RUN mkdir /storage
RUN chown -R $USER:$USER /storage
RUN chown -R $USER:$USER /home/$USER
RUN touch /home/$USER/.sudo_as_admin_successful
