version: "3.7"
   
services:
  emacs:
    image: ghcr.io/nakkaya/emacs-cpu:latest
    privileged: true
    security_opt:
      - seccomp:unconfined
    hostname: emacsd
    restart: always
    volumes:
      - storage:/storage
      - emacs_db:/home/core/.emacs.d
    ports:
      # SSH
      - "2222:22"
      # Webdav
      - "4242:4242"
      # GUI
      - "9090:9090"
    #environment:
      #- PASSWD=pass

volumes:
  emacs_db:
  storage:
