[program:opencode]
stopasgroup=true
directory=/storage
command=/opt/opencode/bin/opencode web --port 49168 --hostname 0.0.0.0
stdout_logfile=/opt/emacsd/logs/opencode.log
stdout_logfile_maxbytes=0
stderr_logfile=/opt/emacsd/logs/opencode.log
stderr_logfile_maxbytes=0
autostart=false
autorestart=true
startsecs=10
stopwaitsecs = 60
