#!/usr/bin/env bash

if [ ! -f gotty ]; then
    wget https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
    tar -xf gotty_linux_amd64.tar.gz
fi

LOG_FILE="daemon.log"
PID_FILE="daemon.pid"

case "$1" in
    start)
        echo "Starting Emacs Daemon"
        ./gotty -w /usr/bin/emacsclient --tty -a '' > $LOG_FILE 2>&1 &
        echo $! > $PID_FILE
        ;;
    stop)
        echo "Shutting Emacs Daemon"
        kill -9 `cat $PID_FILE`
        rm $PID_FILE
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if [ -f "$PID_FILE" ]; then
            echo "Running"
        else 
            echo "Stopped"
        fi

        ;;
    *)
        ## If no parameters are given, print which are avaiable.
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
