name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 10 * * 1'  # Run at 10:00 on Monday.

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      sign: false
      context: docker
      file: docker/Dockerfile
      meta-images: |
        nakkaya/emacs
        ghcr.io/nakkaya/emacs
      meta-tags: |
        type=raw,value=latest
        type=sha
    secrets:
      registry-auths: |
        - registry: docker.io
          username: nakkaya
          password: ${{ secrets.DOCKER_PASSWORD }}
        - registry: ghcr.io
          username: nakkaya
          password: ${{ secrets.GHCR_PASSWORD }}
